### ISSUE TITLE
Wrong author displayed in "Latest Activities"

### ISSUE THREAD

**Issue by bchanudet** [scm-manager/scm-landingpage-plugin#25]
## Issue description

Hi,

I've noticed a strange bug in the "Latest activities" part of the landing page plugin. The author of the action is wrong for most of the lines. This brings confusion because some users do not have access to some repositories, but they appear as authors of the latest commit.

#### Describe how to reproduce the bug

I don't know exactly how to trigger this error. It happened kind of organically. Once I click on the repository link to access the commit history, it appears as expected with the correct authors. I've provided screnshot towards the end of this note.

#### Describe your SCM-Manager setup

I detected this bug some versions ago. I updated right now to v2.16.0 but to no avail.

Plugins used on this server: 
- Activity
- Author Mapping
- Gravatar
- Readme
- Statistic
- Landingpage
- Notify
- Webhook

SCM is installed on a Debian container on a Proxmox server, and is updated from your APT repository.

#### Screenshots

1. Latest activity panel
![2021-03-29 19_12_16-Window](https://user-images.githubusercontent.com/5636773/112875967-2cd44d00-90c5-11eb-8552-e6b435be3168.png)
2. `test/application` commit history
![2021-03-29 19_16_03-Window](https://user-images.githubusercontent.com/5636773/112876199-7fae0480-90c5-11eb-9b25-464104f5de7f.png)
3. `dragon/frontend` commit history
![2021-03-29 19_18_52-Window](https://user-images.githubusercontent.com/5636773/112876248-918fa780-90c5-11eb-8209-3d97d855d98a.png)

Errors detected:
- **Serge Delbroc** doesn't have access to **test/application**, but has access to **aristotle/frontend**
- **Armand Mollet** doesn't have access to **dragon/frontend**, but has access to **test/application**
- The last commit pushed on **test/application** is actually from **Bruno Almand**
- I'm actually the author of the last commit in **dragon/frontend**

If there is anything I can do to help, please let me know. :) 

Regards,

**Comment by pfeuffer** [comment]
Thanks for the report. We will take a look at it.

**Comment by sdorra** [comment]
@bchanudet Does the error still occur for new commits with the 2.16.0?

**Comment by bchanudet** [comment]
@sdorra I waited a few days to have several new commits displayed and indeed, it looks like the error doesn't occur with the 2.16.0 version.

Does it mean the bug was not really coming from the plugin but from another part of the system? 

Anyway, I think we can close this issue. Thanks for your support! :)

**Comment by sdorra** [comment]
@bchanudet yes the bug was related to our event processing system and is fixed with the 2.16.0 release:

> Wrong subject context for asynchronous subscriber (scm-manager/scm-manager#1601)
