### ISSUE TITLE
Wrong Link in Plugin Update Task

### ISSUE THREAD

**Issue by Shaoranlaos** [scm-manager/scm-landingpage-plugin#54]
#### Describe how to reproduce the bug

When there is an update for a plugin and the landingpage-plugin is installed, the update is shown in the task list of an admin.
The click on this task should link to the plugin admin page but does not:
current Link: https://example.com/scm/repo/admin/plugins/installed/
correct Link: https://example.com/scm/admin/plugins/installed/

#### Describe your SCM-Manager setup

SCM 2.18.0
landingpage-plugin 1.9.0
via nginx proxy

#### Which operating system, browser and versions do you use?

Server: CentOS 7
Client: Windows with Chrome 86

#### Further Information
![image](https://user-images.githubusercontent.com/25054970/147923615-f08c10e6-2ea7-4f4c-b37b-81e2146dc51e.png)

**Comment by eheimbuch** [comment]
Hey @Shaoranlaos,

thanks for your report. We missed an slash there. -.- 
It is already fixed and released with version [1.9.1](https://scm-manager.org/plugins/scm-landingpage-plugin/releases/).

Kind Regards
