### ISSUE TITLE
Custom String in place of "mySCM"

### ISSUE THREAD

**Issue by namandixit** [scm-manager/scm-landingpage-plugin#66]
#### Problem to be solved

On the Landing Page, there is a title on the top that reads "mySCM". Since SCM Manager doesn't really seem to provide any method to brand the instance, allowing the users to edit this string to a custom value will provide a simple way to visually specify the instance name.

#### Proposed solution

In the Settings options, an entry for this plugin can be added, which allows entering a custom string to be used on the landing page in place of "mySCM"

**Comment by christophloose** [comment]
Hey @namandixit we share your feeling and will implement this feature soon. Stay tuned

**Comment by pfeuffer** [comment]
We've just release version 1.17.0 of the landingpage plugin (available for SCM-Manager 2.48.x). You will find the setting in "Administration - Settings - Landingpage". Thanks for the suggestion.
